apiVersion: apps/v1
kind: Deployment
metadata:
  name: n1an-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: n1an-guestbook
      component: n1an-frontend
  template:
    metadata:
      labels:
        app: n1an-guestbook
        component: n1an-frontend
    spec:
      containers:
        - name: n1an-frontend
          image: ghcr.io/billare/guestbook-frontend:latest   #
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: n1an-frontend
spec:
  type: ClusterIP
  selector:
    app: n1an-guestbook
    component: n1an-frontend
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: n1an-argocd:route.openshift.io/Route:grupp3/n1an-frontend
  name: n1an-frontend
  namespace: grupp3
spec:
  port:
    'targetPort': 8080
  to:
    kind: Service
    name: n1an-frontend
