# PostgreSQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n1an-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: lvms-vg1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n1an-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n1an-postgres
  template:
    metadata:
      labels:
        app: n1an-postgres
    spec:
      containers:
        - name: n1an-postgres
          image: quay.io/fedora/postgresql-16:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: n1an-db-password
                  key: username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n1an-db-password
                  key: password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: n1an-db-config
                  key: db-name
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: n1an-postgres
spec:
  type: ClusterIP
  selector:
    app: n1an-postgres
  ports:
    - port: 5432
---
# Redis
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n1an-redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: lvms-vg1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n1an-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n1an-redis
  template:
    metadata:
      labels:
        app: n1an-redis
    spec:
      containers:
        - name: n1an-redis
          image: quay.io/kurs/redis:latest
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n1an-redis-password
                  key: password
          volumeMounts:
            - name: n1an-redis-data
              mountPath: /var/lib/redis/data
      volumes:
        - name: n1an-redis-data
          persistentVolumeClaim:
            claimName: n1an-redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: n1an-redis
spec:
  type: ClusterIP
  selector:
    app: n1an-redis
  ports:
    - port: 6379

# Golang Backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n1an-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: n1an-backend
  template:
    metadata:
      labels:
        app: n1an-backend
    spec:
      containers:
        - name: n1an-backend
          image: quay.io/hardo314/golang-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: n1an-db-config
                  key: n1an-db-host
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: n1an-db-config
                  key: n1an-redis-host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: n1an-db-config
                  key: n1an-redis-port
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n1an-redis-password
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: n1an-backend
spec:
  type: ClusterIP
  selector:
    app: n1an-backend
  ports:
    - port: 8080
